# Generated by Django 4.1 on 2022-08-25 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notice', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
